name: darielxz-external

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Obtener codigo del repositorio
        uses: actions/checkout@v4

      - name: Seleccionar version de Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app

      - name: Compilar Proyecto (.app)
        run: |
          xcodebuild build \
            -project ThreeOneOSFive.xcodeproj \
            -scheme 3105 \
            -sdk iphoneos \
            -configuration Release \
            -derivedDataPath build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
            
      - name: Copiar parches a la carpeta Documents
        run: |
          APP_PATH=$(find build/Build/Products/Release-iphoneos -name "*.app" -maxdepth 1)
          mkdir -p "$APP_PATH/Documents"
          cp Resources/*.3105 "$APP_PATH/Documents/"

      - name: Empaquetar en archivo .IPA
        run: |
          mkdir -p Payload
          cp -r build/Build/Products/Release-iphoneos/*.app Payload/
          zip -r darielxz-external.ipa Payload

      - name: Subir ejecutable IPA
        uses: actions/upload-artifact@v4
        with:
          name: darielxz-external-ipa
          path: darielxz-external.ipa
