name: darielxz-external

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Obtener codigo del repositorio
        uses: actions/checkout@v4

      - name: Seleccionar version de Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app

      - name: Compilar Proyecto (.app)
        run: |
          xcodebuild build \
            -project ThreeOneOSFive.xcodeproj \
            -scheme 3105 \
            -sdk iphoneos \
            -configuration Release \
            -derivedDataPath build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Preparar y desplegar parches en Documents/Patches
        run: |
          APP_PATH=$(find build/Build/Products/Release-iphoneos -name "*.app" -maxdepth 1)
          PATCHES_DIR="$APP_PATH/Documents/Patches"
          
          mkdir -p "$PATCHES_DIR"
          
          for patch in Resources/*.3105; do
            if [ -f "$patch" ]; then
              filename=$(basename -- "$patch")
              foldername="${filename%.*}"
              
              mkdir -p "$PATCHES_DIR/$foldername"
              unzip -q "$patch" -d "$PATCHES_DIR/$foldername/"
            fi
          done

      - name: Empaquetar en archivo .IPA
        run: |
          mkdir -p Payload
          cp -r build/Build/Products/Release-iphoneos/*.app Payload/
          zip -r darielxz-external.ipa Payload

      - name: Subir ejecutable IPA
        uses: actions/upload-artifact@v4
        with:
          name: darielxz-external-ipa
          path: darielxz-external.ipa
